### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DubyaDude** [expenses/RT-Video-Downloader#4]
Pick an option:
D to enter in the url of a video and download it.
I to manually enter in a index.m3u8 playlist and download a video.
J to concatenate downloaded files into a single file.
X to exit.
D

Enter the url of the video:
http://roosterteeth.com/episode/rwby-season-3-chapter-2-new-challengers
An index.m3u8 file was not found. Please check that you have entered the correct url and that the video isn't on youtube instead.

**Comment by DubyaDude** [comment]
Ok, I see they changes where they put their m3u8 file

Like here's it for RWBY Chapter 1:
http://wpc.1765A.taucdn.net/801765A/video/uploads/videos/df9809ff-d810-484e-9fb6-f28e064d2819/index.m3u8
And here it is for Chapter 2: 
http://wpc.1765A.taucdn.net/801765A/video/uploads/videos/af7dde84-1fba-428b-8269-32496a33e26e/index.m3u8

**Comment by expenses** [comment]
The script won't work for videos that are out for subscribers-only, as the index.m3u8 file isn't linked on the page if you aren't a logged-in subscriber. You'll have to get the link manually or off someone who is a subscriber.
